
# conda environment
#
# Copyright 2021 John Hanley. MIT licensed.

name: changepoint

channels:
  - conda-forge

dependencies:
  - flake8 >= 3.8.4
  - isort >= 5.7.0
  - matplotlib >= 3.3.4
  - pip >= 21.0.1
  - python >= 3.9.2
  - requests >= 2.25.1
  - ruptures >= 1.1.3
  - ruamel.yaml >= 0.16.12
  - scipy >= 1.6.0
  - tqdm >= 4.58.0
  - pip:
    - uszipcode >= 0.2.4
